"""empty message

Revision ID: 3a412b31d43e
Revises: e9f87ed167be
Create Date: 2016-07-28 14:13:53.005537

"""

# revision identifiers, used by Alembic.
revision = '3a412b31d43e'
down_revision = 'e9f87ed167be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('username', sa.Text(), nullable=True))
    op.drop_constraint('posts_u_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'u_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('u_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_u_id_fkey', 'posts', 'users', ['u_id'], ['id'])
    op.drop_column('posts', 'username')
    ### end Alembic commands ###
