"""empty message

Revision ID: e9f87ed167be
Revises: 6fdac9fd8b71
Create Date: 2016-07-28 11:28:17.271418

"""

# revision identifiers, used by Alembic.
revision = 'e9f87ed167be'
down_revision = '6fdac9fd8b71'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.Text(), nullable=True))
    op.drop_constraint('users_user_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['name'])
    op.drop_column('users', 'user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_user_key', 'users', ['user'])
    op.drop_column('users', 'name')
    ### end Alembic commands ###
